name: build

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 8

      - name: Build
        run: ./gradlew assembleNormalArmDebug
        working-directory: Hin2n_android

      - name: Sign
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: Hin2n_android/app/build/outputs/apk/normalArm/debug
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: hin2n
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          if-no-files-found: error
