name: build

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 8

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew assembleNormalArmDebug
        working-directory: Hin2n_android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Hin2n APK
          path: Hin2n_android/app/build/outputs/apk/arm/debug/hin2n_v1.0-rc1_4_arm64-v8a.apk
